=== Anubhav/eclipse-swordfish/org.eclipse.swordfish.configrepos.shared/test/resources/xml/sbb_conf_sbblocalcfg.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--============================================================================
    Copyright (c) 2007 Deutsche Post AG.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
    
    Contributors:
       Deutsche Post AG - initial API and implementation
 ============================================================================-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AuthenticationProcessor">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CredentialLoginType">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="auth-id-password"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="AssertionLoginType">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="auth-token-checking"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="LdapURL" type="xs:anyURI"/>
							<xs:element name="JAASConfigFile" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="optional" default="default"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="AuthorizationProcessor">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="KeystorePassword" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="optional" default="default"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="SigningProcessor">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CheckCertificateValidity" type="xs:boolean"/>
							<xs:element name="CheckCertificateIssuerTrust" type="xs:boolean"/>
							<xs:element name="CheckCertificateSignature" type="xs:boolean"/>
							<xs:element name="CheckCertificateRevocation" type="xs:boolean"/>
							<xs:element name="KeyStorePassword" type="xs:string"/>
							<xs:element name="KeyPassword" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="optional" default="default"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ContextStore">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="LdapURL" type="xs:anyURI"/>
							<xs:element name="LdapUser" type="xs:string"/>
							<xs:element name="LdapPassword" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="optional" default="default"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Anubhav/eclipse-swordfish/org.eclipse.swordfish.configrepos.shared/test/resources/xml/sbb_confinst_sbblocalcfg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--============================================================================
    Copyright (c) 2007 Deutsche Post AG.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
    
    Contributors:
       Deutsche Post AG - initial API and implementation
 ============================================================================-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.sbb.org/sbb-conf/local/SBB
C:\Daten\dpag\Schemas-TSP-config\done\sbb_conf_sbblocalcfg.xsd">
	<!--  -->
	<AuthenticationProcessor name="default">
		<CredentialLoginType>auth-id-password</CredentialLoginType>
		<AssertionLoginType>auth-token-checking</AssertionLoginType>
		<LdapURL>ldap://192.168.100.68:1389/o=ubbrief.deutschepost.de</LdapURL>
		<JAASConfigFile>ldap_jaas.config</JAASConfigFile>
	</AuthenticationProcessor>
	<!--  -->
	<AuthorizationProcessor name="default">
		<KeystorePassword>password</KeystorePassword>
	</AuthorizationProcessor>
	<!--  -->
	<SigningProcessor name="default">
		<CheckCertificateValidity>false</CheckCertificateValidity>
		<CheckCertificateIssuerTrust>false</CheckCertificateIssuerTrust>
		<CheckCertificateSignature>false</CheckCertificateSignature>
		<CheckCertificateRevocation>false</CheckCertificateRevocation>
		<KeyStorePassword>test</KeyStorePassword>
		<KeyPassword>test</KeyPassword>
	</SigningProcessor>
	<ContextStore name="default">
		<LdapURL>ldap://sopsparc08-5.servicebackbone.org:40389/o=SOPware</LdapURL>
		<LdapUser>cn=admin ,o=SOPware</LdapUser>
		<LdapPassword>secret</LdapPassword>
	</ContextStore>
</config>
