=== Anubhav/eclipse-swordfish/org.eclipse.swordfish.configrepos.shared/test/resources/xml/sbb_conf_remotefallbackcfg.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--============================================================================
    Copyright (c) 2007 Deutsche Post AG.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
    
    Contributors:
       Deutsche Post AG - initial API and implementation
 ============================================================================-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Kernel">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="MinThreadCount" type="xs:nonNegativeInteger"/>
							<xs:element name="MaxThreadCount" type="xs:nonNegativeInteger"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="optional" default="default"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="AuthorizationProcessor">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ExpiryClearance" type="xs:nonNegativeInteger"/>
							<xs:element name="ClientExpiry" type="xs:boolean"/>
							<xs:element name="ClientVerification" type="xs:boolean"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="optional" default="default"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="AuthenticationProcessor">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="UsernameTokenSupportOperation">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Operation">
											<xs:complexType>
												<xs:attribute name="value" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="optional" default="default"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="PolicyRouter">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="PolicyExpiryCheck" type="xs:boolean"/>
							<xs:element name="PolicyExpiryGracePeriod" type="xs:nonNegativeInteger"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="optional" default="default"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="PolicyResolver">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="PolicyMap">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Policy" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Key" type="xs:string"/>
													<xs:element name="Resource" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="DefaultPolicyName" type="xs:string" default="StandardPolicy" minOccurs="0"/>
							<xs:element name="UseDefaultConsumerPolicy" type="xs:boolean" default="true" minOccurs="0"/>
							<xs:element name="DefaultConsumerPolicyName" type="xs:string" default="DefaultConsumerPolicy" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="optional" default="default"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ContextStore">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="LdapURL" type="xs:anyURI"/>
							<xs:element name="LdapUser" type="xs:string"/>
							<xs:element name="LdapPassword" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="optional" default="default"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Anubhav/eclipse-swordfish/org.eclipse.swordfish.configrepos.shared/test/resources/xml/sbb_confinst_remotefallbackcfg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--============================================================================
    Copyright (c) 2007 Deutsche Post AG.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
    
    Contributors:
       Deutsche Post AG - initial API and implementation
 ============================================================================-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.sbb.org/sbb-conf/remote/SBB
C:\Daten\dpag\Schemas-TSP-config\done\sbb_conf_remotefallbackcfg.xsd">
	<Kernel name="default">
		<MinThreadCount>5</MinThreadCount>
		<MaxThreadCount>10</MaxThreadCount>
	</Kernel>
	<AuthorizationProcessor name="default">
		<ExpiryClearance>20</ExpiryClearance>
		<ClientExpiry>false</ClientExpiry>
		<ClientVerification>false</ClientVerification>
	</AuthorizationProcessor>
	<AuthenticationProcessor name="default">
		<UsernameTokenSupportOperation>
			<Operation value="seekBook"/>
		</UsernameTokenSupportOperation>
	</AuthenticationProcessor>
	<PolicyRouter name="default">
		<!-- Defines whether agreed policies should be checked for expiry -->
		<PolicyExpiryCheck>false</PolicyExpiryCheck>
		<!-- Grace period in seconds to consider when checking for policy expiry -->
		<PolicyExpiryGracePeriod>600</PolicyExpiryGracePeriod>
	</PolicyRouter>
	<PolicyResolver name="default">
		<PolicyMap>
			<Policy>
				<Key>FastAndFurious</Key>
				<Resource>consumer.ppdx</Resource>
			</Policy>
			<Policy>
				<Key>DefaultConsumerPolicy</Key>
				<Resource>consumer.ppdx</Resource>
			</Policy>
			<Policy>
				<Key>StandardPolicy</Key>
				<Resource>consumer.ppdx</Resource>
			</Policy>
		</PolicyMap>
		<DefaultPolicyName>StandardPolicy</DefaultPolicyName>
		<UseDefaultConsumerPolicy>true</UseDefaultConsumerPolicy>
		<DefaultConsumerPolicyName>DefaultConsumerPolicy</DefaultConsumerPolicyName>
	</PolicyResolver>
	<ContextStore name="default">
		<LdapURL>ldap://sopsparc08-5.servicebackbone.org:50389/o=sop.sbb.org</LdapURL>
		<LdapUser>cn=admin ,o=sop.sbb.org</LdapUser>
		<LdapPassword>secret</LdapPassword>
	</ContextStore>
</config>
