=== Anubhav/eclipse-swordfish/org.eclipse.swordfish.configrepos.shared/test/resources/xml/tsp_conf_notificationReceiver-local.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--============================================================================
    Copyright (c) 2007 Deutsche Post AG.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
    
    Contributors:
       Deutsche Post AG - initial API and implementation
 ============================================================================-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="LdapStoreOperation">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ProviderURL" type="xs:anyURI"/>
							<xs:element name="BaseDN" type="xs:string"/>
							<xs:element name="UserDN" type="xs:string"/>
							<xs:element name="Credentials" type="xs:string"/>
							<xs:element name="Pattern" type="xs:string"/>
							<xs:element name="RetryCount" type="xs:nonNegativeInteger"/>
							<xs:element name="RetryTime" type="xs:nonNegativeInteger"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="optional" default="default"/>						
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Anubhav/eclipse-swordfish/org.eclipse.swordfish.configrepos.shared/test/resources/xml/tsp_confinst_notificationReceiver-local.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--============================================================================
    Copyright (c) 2007 Deutsche Post AG.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
    
    Contributors:
       Deutsche Post AG - initial API and implementation
 ============================================================================-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.sbb.org/tsp-conf/local/NotificationReceiver
C:\Daten\dpag\Schemas-TSP-config\done\tsp_conf_notificationReceiver-local.xsd">
	<LdapStoreOperation name="default">
		<ProviderURL>ldap://localhost:389/o=sop.sbb.org</ProviderURL>
		<!-- <providerURL>ldap://sopsparc08-5.servicebackbone.org:60389/o=sop.sbb.org"/> -->
		<BaseDN>ou=mss</BaseDN>
		<UserDN>cn=admin,o=sop.sbb.org</UserDN>
		<Credentials>secret</Credentials>
		<!-- Pattern, which is used to convert java.util.Date into String before storing it in a LDAP directory -->
		<Pattern>yyyy-MM-dd'T'HH:mm:ss'.'SSS'Z'</Pattern>
		<RetryCount>3</RetryCount>
		<!--in seconds-->
		<RetryTime>5</RetryTime>
	</LdapStoreOperation>
</configuration>
